AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'my-s3-bucket-339713007551'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: The name of the S3 bucket
    Value: !Ref S3Bucket
